default_sqlt3: &default_sqlt3
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock
  username: root
  password: <%= ENV.fetch("DB_PASSWORD", 'my_password') %>

development:
  <<: *default
  database: graph_mem

test:
  <<: *default
  database: graph_mem_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: graph_mem
  cache:
    <<: *default_sqlt3
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default_sqlt3
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default_sqlt3
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
